# Generated by Django 4.1.6 on 2023-02-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_title',
            new_name='title',
        ),
    ]
